version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "9000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DATABASE_URL=postgresql://user:password@db/matches

  frontend:
    build: ./frontend
    ports:
      - "4000:3000"

  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: matches
    ports:
      - "6299:5432"

  redis:
    image: redis
    ports:
      - "6380:6379"

